network:
  master_servers:
    - hostname: master-01
      ip_address: 0.0.0.0
      port: 50051
  chunk_servers:
    - hostname: chunk-server-01
      ip_address: 0.0.0.0
      port: 50052
    - hostname: chunk-server-02
      ip_address: 0.0.0.0
      port: 50053
    - hostname: chunk-server-03
      ip_address: 0.0.0.0
      port: 50054

disk:
  # The block size (MB) for each GFS file chunk
  - block_size_mb: 64
  # The minimum disk space (MB) that a chunk server has to maintain
  - min_disk_space_mb: 100

timeout:
  # The valid suffixes are "ns", "us" "ms", "s", "m", and "h".
  - grpc: 10s
  - heartbeat: 30s
  - client_cache: 10m
