load("@rules_cc//cc:defs.bzl", "cc_library")

cc_library(
    name = "utils",
    srcs = ["utils.cc"],
    hdrs = ["utils.h"],
    visibility = ["//visibility:public"],
    deps = [
        "@boringssl//:crypto",
        "@com_github_grpc_grpc//:grpc++",
        "@com_google_absl//absl/crc:crc32c",
        "@com_google_absl//absl/status",
        "@com_google_absl//absl/status:statusor",
        "@com_google_absl//absl/strings",
        "@com_google_absl//absl/synchronization",
        "@parallel_hashmap",
        "@yaml_cpp//:yaml-cpp",
    ],
)

cc_library(
    name = "protos_common",
    hdrs = ["protos_common.h"],
    visibility = ["//visibility:public"],
    deps = ["//src/protos:cc_chunk_server_proto"],
)

cc_library(
    name = "system_logger",
    srcs = ["system_logger.cc"],
    hdrs = ["system_logger.h"],
    visibility = ["//visibility:public"],
    deps = ["@com_google_glog//:glog"],
)

cc_library(
    name = "config_manager",
    srcs = ["config_manager.cc"],
    hdrs = ["config_manager.h"],
    visibility = ["//visibility:public"],
    deps = [
        ":utils",
        "//src/protos:cc_chunk_server_proto",
        "@com_google_absl//absl/container:flat_hash_set",
        "@com_google_absl//absl/status",
        "@com_google_absl//absl/status:statusor",
        "@com_google_absl//absl/strings",
        "@com_google_absl//absl/time",
        "@yaml_cpp//:yaml-cpp",
    ],
)
